=== eliz-bzh/WebLabs/XML/Божкова_ЛР13 Т-795(xml)/lr3/task4/task4.xsd
<?xml version="1.0" encoding="Windows-1251"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:complexType name="TitleType">
        <xsd:simpleContent>
            <xsd:restriction base="xsd:string">
                <xsd:attribute name="number" type="xsd:integer" use="required" />
            </xsd:restriction>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="numberType">
        <xsd:simpleContent>
            <xsd:restriction base="xsd:integer"></xsd:restriction>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:element name="GOODS">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="header" minOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Title" type="TitleType">
                                <xsd:element name="message" minOccurs="1" type="messageType" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="PILS">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="HEAD">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="PILL">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="Name" type="xsd:string" />
                                                    <xsd:element name="Weight" type="xsd:string" />
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="STOMAC">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="PILL">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <!-- Возможно их можно было вынести в отдельный тип и переиспользовать но я не хз-->
                                                    <xsd:element name="Name" type="xsd:string" />
                                                    <xsd:element name="Weight" type="xsd:string" />
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="MIXTURES">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="PROSTUDA">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="MIXTURE">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="Name" type="xsd:string" />
                                                    <xsd:element name="Weight" type="xsd:string" />
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="STOMAC">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="MIXTURE">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="Name" type="xsd:string" />
                                                    <xsd:element name="Weight" type="xsd:string" />
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== eliz-bzh/WebLabs/XML/Божкова_ЛР13 Т-795(xml)/lr3/task4/task3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- товары -->
<GOODS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="task4.xsd">
<header>
        <Title number="1">
            Название
        </Title>
        <Title number="2">Вес в граммах</Title>
    </header>
    <!-- таблетки -->
    <PILS>
        <!-- таблетки от головы -->
        <HEAD>
            <!-- Таблетка  -->
            <PILL>
                <!-- название -->
                <Name>
                    Анальгин
                </Name>
                <!-- вес -->
                <Weight>
                    15 грамм
                </Weight>
            </PILL>
            <!-- Таблетка  -->
            <PILL>
                <!-- название -->
                <Name>
                    Ношпа
                </Name>
                <!-- вес -->
                <Weight>
                    20 грамм
                </Weight>
            </PILL>
            <!-- Таблетка  -->
            <PILL>
                <!-- название -->
                <Name>
                    Парацетомол
                </Name>
                <!-- вес -->
                <Weight>
                    12 грамм
                </Weight>
            </PILL>
        </HEAD>
        <!-- таблетки от живота -->
        <STOMAC>
           <!-- таблетка -->
            <PILL>
                <!-- название -->
                <Name>
                    Уголь
                </Name>
                <!-- вес -->
                <Weight>
                    11 грамм
                </Weight>
            </PILL>
           <!-- таблетка -->
            <PILL>
                <!-- название -->
                <Name>
                    Фестал
                </Name>
                <!-- вес -->
                <Weight>
                    24 грамма
                </Weight>
            </PILL>
        </STOMAC>
    </PILS>
    <!-- микстуры -->
    <MIXTURES>
        <!-- микстуры от простуды -->
        <PROSTUDA>
            <!-- микстура -->
            <MIXTURE>
                <!-- название -->
                <Name>
                    АЦЦ
                </Name>
                <!-- объем -->
                <Weight>
                    50 миллилитров
                </Weight>
            </MIXTURE>
            <!-- микстура -->
             <MIXTURE>
                <!-- название -->
                <Name>
                    Антигриппин
                </Name>
                <!-- объем -->
                <Weight>
                    47 грамм
                </Weight>
            </MIXTURE>
        </PROSTUDA>
        <!-- микстуры от живота -->
        <STOMACS>
            <!-- микстура -->
            <MIXTURE>
            <!-- название -->
                <Name>
                    Аллахол
                </Name>
                <!-- объем -->
                <Weight>
                    35 миллилитров
                </Weight>
            </MIXTURE>
            <!-- микстура -->
             <MIXTURE>
                <!-- название -->
                <Name>
                    Энтерфурицин
                </Name>
                <!-- объем -->
                <Weight>
                    44 миллилитра
                </Weight>
            </MIXTURE>
        </STOMACS>
    </MIXTURES>
</GOODS>
