=== eliz-bzh/WebLabs/XML/Божкова_ЛР12 Т-795(xml)/task2/Video.dtd
<!ELEMENT VIDEO (main, VID, MemorySupport, configure, connectors, interfaces, coulers, supply, compability, logistic)>
<!ELEMENT main (manufacturer, model, length)>
<!ELEMENT VID (videoMemory, RAMDAC, maximumResolution2D3D, HDCP, API)>
<!ELEMENT MemorySupport (type, memoryBusWidth, memoryFrequency)>
<!ELEMENT configure (chip, techprocess, chipFrequency, pixelsConveers, processors)>
<!ELEMENT interfaces (interface)>
<!ELEMENT coulers (speedControl, cool, constructionCoolSystem)>
<!ELEMENT supply (powerConnector)>
<!ELEMENT compatibility (systemPermitions, computingSupport, OSSuppurt)>
<!ELEMENT logistic (size, wightBrutal)>

<!ELEMENT Manufacturer (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT videoMemory (#PCDATA)>
<!ELEMENT RAMDAC (#PCDATA)>
<!ELEMENT maximumResolution2D3D (#PCDATA)>
<!ELEMENT HDCP (#PCDATA)>
<!ELEMENT API (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT memoryBusWidth (#PCDATA)>
<!ELEMENT memoryFrequency (#PCDATA)>
<!ELEMENT chip (#PCDATA)>
<!ELEMENT techprocess (#PCDATA)>
<!ELEMENT chipFrequency (#PCDATA)>
<!ELEMENT pixelsConveers (#PCDATA)>
<!ELEMENT processors (#PCDATA)>
<!ELEMENT connectors (ports)>
<!ELEMENT ports (#PCDATA)>
<!ELEMENT interface (#PCDATA)>
<!ELEMENT speedControl (#PCDATA)>
<!ELEMENT cool (#PCDATA)>
<!ELEMENT constructionCoolSystem (#PCDATA)>
<!ELEMENT powerConnector (#PCDATA)>
<!ELEMENT systemPermitions (#PCDATA)>
<!ELEMENT computingSupport (#PCDATA)>
<!ELEMENT OSSuppurt (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT wightBrutal (#PCDATA)>

<!ATTLIST manufacturer title CDATA #REQUIRED>
<!ATTLIST model title CDATA #REQUIRED>
<!ATTLIST videoMemory title CDATA #REQUIRED>
<!ATTLIST RAMDAC title CDATA #REQUIRED>
<!ATTLIST maximumResolution2D3D title CDATA #REQUIRED>
<!ATTLIST HDCP title CDATA #REQUIRED>
<!ATTLIST API title CDATA #REQUIRED>
<!ATTLIST type title CDATA #REQUIRED>
<!ATTLIST memoryBusWidth title CDATA #REQUIRED>
<!ATTLIST memoryFrequency title CDATA #REQUIRED>
<!ATTLIST chip title CDATA #REQUIRED>
<!ATTLIST techprocess title CDATA #REQUIRED>
<!ATTLIST chipFrequency title CDATA #REQUIRED>
<!ATTLIST pixelsConveers title CDATA #REQUIRED>
<!ATTLIST processors title CDATA #REQUIRED>
<!ATTLIST ports title CDATA #REQUIRED>
<!ATTLIST interface title CDATA #REQUIRED>
<!ATTLIST speedControl title CDATA #REQUIRED>
<!ATTLIST cool title CDATA #REQUIRED>
<!ATTLIST constructionCoolSystem title CDATA #REQUIRED>
<!ATTLIST supply title CDATA #REQUIRED>
<!ATTLIST powerConnector title CDATA #REQUIRED>
<!ATTLIST systemPermitions title CDATA #REQUIRED>
<!ATTLIST computingSupport title CDATA #REQUIRED>
<!ATTLIST OSSuppurt title CDATA #REQUIRED>
<!ATTLIST size title CDATA #REQUIRED>
<!ATTLIST wightBrutal title CDATA #REQUIRED>

=== eliz-bzh/WebLabs/XML/Божкова_ЛР12 Т-795(xml)/task2/Video.xml
<?xml version = "1.0" encoding="UTF-8"?>
<!DOCTYPE VIDEO SYSTEM "Video.dtd">

<VIDEO>
    <main>
        <manufacturer title="производитель">ASUS</manufacturer>
        <model title="модель">EAH5670/DI/512MD5</model>
        <length title="длина">170 mm</length>
    </main>
    <VID>
        <videoMemory title="количество видеопамяти">512 mb</videoMemory>
        <RAMDAC title="RAMDAC">400 mg gc, 10 бит на канал</RAMDAC>
        <maximumResolution2D3D title="Максимальное разрешение 2D/3d">2560 x 1600 при подключении DVI или DisplayPort 2048 x 1536, 2048 x 1536 1920x1200 при подключении по HDMI</maximumResolution2D3D>
        <HDCP title="HDCP">Есть (1080p)</HDCP>
        <API title="API">DirectX 11 OpenGL 3.2</API>
    </VID>
    <MemorySuport>
        <type title="Тип">GDDR5</type>
        <memoryBusWidth title="Размер шины памяти">128 бит</memoryBusWidth>
        <memoryFrequency title="Частота памяти">1000 МГц</memoryFrequency>
    </MemorySuport>
    <configure>
        <chip title="Чип">Radeon HD 5670</chip>
        <techprocess title="Техпроцесс">40 нм</techprocess>
        <chipFrequency title="Частота чипа">775 МГц</chipFrequency>
        <pixelsConveers title="кол-во пиксельных конвееров ">20, 8 блоков выборки текстур</pixelsConveers>
        <processors title="Процессор">400</processors>
    </configure>
    <connectors>
        <ports title="Порты">DVI-I, HDMI, 15-пиновый коннектор, D-Sub</ports>
    </connectors>
    <interfaces>
        <interface title="Интерфейс">PCI Express 2.1 16x (совместим с PCI Express 1.x) с возможностью объеденения карт при помощи CrossfireX</interface>
    </interfaces>
    <coulers>
        <speedControl title="Управление скоростью">Нет</speedControl>
        <cool title="Охлаждение">Активное (радиатор с вентилятором)</cool>
        <constructionCoolSystem title="Конструкция системы охлаждения">Система охлаждения блокирует соседний с видеокартой слот расширения</constructionCoolSystem>
    </coulers>
    <supply>
        <powerConnector title="Разъем питания">Нет</powerConnector>
    </supply>
    <compatibility>
        <systemPermitions title="Системные требования">Блок питания мощностью 400 Вт или 500 Вт для двух видеокарт в режиме CrossFire</systemPermitions>
        <computingSupport title="Поддержка вычислений общего назначения">ATI stream, OpenCL 1.0, DirectCompute 11</computingSupport>
        <OSSuppurt title="Поддержка Ос">Windows XP x64, Windows XP, Windows MCE 2005, Windows Vista, Windows 7</OSSuppurt>
    </compatibility>
    <logistic>
        <size title="Размер упаковки">30.5 x 22.5 x 5.7 cм</size>
        <wightBrutal title="Масса брутто">0.775 кг</wightBrutal>
    </logistic>
</VIDEO>
